### ISSUE TITLE
Handling ordering and filtering in nodes based on a 1:1 connection fields

### ISSUE THREAD

**Issue by ivosabev** [graphql/graphql-relay-js#105]
I believe this is a very common issue, but couldn't find any helpful resources on how to order or filter the nodes based on a connection field in a 1:1 mapping.

```
{
  userNodes(orderBy: TEAM_NAME) {
    nodes {
      id,
      firstName,
      Team: teamByTeamId {
        name
      }
    }
  }
}
```

It feels very wasteful to get all userNodes with the connection data and then sort in JavaScript.

**Comment by wincent** [comment]
How do you propose to order the collection in a valid way without inspecting everything in the connection? (Unless it is already pre-sorted?) You can of course delegate the task of sorting to your underlying data storage layer, which, given adequate indices, will be able to return a validly-ordered subset of the data in a time-efficient way.

**Comment by ivosabev** [comment]
Unfortunately I do not have a solution, that's why I am asking if this problem has already been though of as it seems very trivial. 

Is there any best practice of doing this or is graphql-realy-js going to offer helpers to simplify the way this is handled. And since performance will rely heavily on cache, who would be responsible for the cache the client or the GraphQL/Relay server?

Thanks!

**Comment by wincent** [comment]
I think before you figure out how to do this with `graphql-relay`, you need to be able to answer this question:

Given a set of records that looks like this:

```
[
  {name: 'foo', id: 1, ...},
  {name: 'bar', id: 2, ...},
  {name: 'baz', id: 3, ...},
  {name: 'qux', id: 4, ...},
  // ... continues for 10,000 more lines
]
```

How do you correctly fulfil a request for "first 10, sorted by name", without looking at all 10,000 items?

**Comment by ivosabev** [comment]
You must look at all. So I guess the only remedy is going down to the data layer level, but what would be the best way to express this in a Relay compliant GraphQL schema?

**Comment by wincent** [comment]
I think that depends on your data storage layer. For example, if your data is in MySQL and you have adequate indices to allow efficiently sorting by `name`, then you could use `connectionFromPromisedArraySlice`. Basically, you construct a query that ends up being something like `SELECT a, b, c FROM blah ORDER BY name OFFSET 500, LIMIT 10` (or whatever), fire off the query, then pass the resulting promise in to `connectionFromPromisedArraySlice`.

I know there are a bunch of libraries out there that people have built (mostly third parties, not FB), that may take care of some (or much) of the actual work of generating SQL (or API calls to your ORM etc), but as this is so specific to each different data layer, it makes most sense for this to reside outside of `graphql-relay` itself. The primitives like `connectionFromArray` and `connectionFromArraySlice` are provided as basic building blocks, but they are pretty simple, so for custom use cases it may make sense to roll your own, or use convenience functions provided by third-party libraries.
