### ISSUE TITLE
add option to connectionDefinitions for forward-only paging

### ISSUE THREAD

**Issue by acarl005** [graphql/graphql-relay-js#112]
The `connectionDefinitions` function has quite a few options for customization. However, it always has the same output fields for the `pageInfo`. When my connections only support forward pagination, I would like to omit `hasPreviousPage` from the `pageInfo`, since `hasPreviousPage` is always false for forward pagination. Something like this would be nice:

``` js
const { connectionType: PostConnection } = connectionDefinitions({ nodeType: Post, forwardOnly: true })
```

As an alternative, maybe just an option to replace the entire `pageInfo` object for the connection, so that way I only have to manually create my `pageInfo` and pass it into the helper instead of having to create the whole connection definition manually.

``` js
const pageInfo = new GraphQLObjectType({ /*...*/ })
const { connectionType: PostConnection } = connectionDefinitions({ nodeType: Post, pageInfo })
```

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
Sadly having a single global `PageInfo` type is mandated by relay connection spec.
