### ISSUE TITLE
How to avoid circular dependency using `connectionDefini

### ISSUE THREAD

**Issue by sibelius** [graphql/graphql-relay-js#113]
I have a circular dependency in my Connection definitions

``` jsx
export default connectionDefinitions({
  name: 'Product',
  nodeType: ProductType,
  connectionFields: {
    count: {
      type: GraphQLInt,
    }
  }
});
```

`ProductType` is undefined in this case

how can I use a `thunk` to solve this?

**Comment by intellix** [comment]
Check out swapi-graphql, they're using a function to resolve types by name:

https://github.com/graphql/swapi-graphql/blob/master/src/schema/relayNode.js#L24

**Comment by leebyron** [comment]
Yep! Use functions that return the set of fields to correct resolve circular dependencies

**Comment by sibelius** [comment]
tks
