### ISSUE TITLE
Q: seems i can not get rootValue in mutation.

### ISSUE THREAD

**Issue by filod** [graphql/graphql-relay-js#12]
https://github.com/graphql/graphql-relay-js/blob/master/src/mutation/mutation.js#L83

I pass user object to rootValue, how can i get user object in mutations ?

**Comment by vslinko** [comment]
Same problem:

I have a function called `wrapField` that checks ACL for concrete field.
Also I have `createSession` mutation that returns `Session` type, but only session owner can read session fields.

Before `graphql-relay` I've used `info.rootValue.user = user` within mutation resolve function but now I can't.

**Comment by dschafer** [comment]
Thanks for the report and PR, just merged!
