### ISSUE TITLE
Are Global Ids relevant when using guids in a NoSQL database

### ISSUE THREAD

**Issue by gruberjl** [graphql/graphql-relay-js#136]
I'm learning GraphQL & your repository. I'll be using a NoSQL database as a backend. Typically I store a random GUID as an ID field in my database.

1 Do I need to use [Object Identification](https://github.com/graphql/graphql-relay-js#object-identification) functions to create global ids when the GUID is already unique?
2 Can I use Relay without the [node root query](https://github.com/graphql/graphql-relay-js/blob/master/src/__tests__/starWarsSchema.js#L237)?
3 Can I implement a node root query without using the globalId?
4 Is it common to use the [Node Defintition](https://github.com/graphql/graphql-relay-js/blob/master/src/__tests__/starWarsSchema.js#L126-L140) with GUIDs?

**Comment by yvann** [comment]
Sure, you can override the way the ID is built in this method : https://github.com/graphql/graphql-relay-js/blob/5927f0becf43740a1f1026c6e960811c4359d342/src/node/node.js#L110

**Comment by gruberjl** [comment]
awesome thanks.
