### ISSUE TITLE
graphql-relay ignores node definitions

### ISSUE THREAD

**Issue by codepreneur** [graphql/graphql-relay-js#142]
My node definitions looks like this:

```
class Store {}
let store = new Store()

let nodeDefs = nodeDefinitions(
  (globalId) => {
    let type = fromGlobalId(globalId).type
    let id = fromGlobalId(globalId).id
    if (type === 'Store') {
      return store
    }
    if (type === 'Video') {
      return docClient.query(
        Object.assign(
          {},
          {TableName: videosTable},
          {KeyConditionExpression: 'id = :id'},
          {ExpressionAttributeValues: { ':id': id }}
        )
      ).promise().then(dataToConnection)

    }
    return null
  },
  (obj) => {
    if (obj instanceof Store) {
      return storeType
    }
    if (obj instanceof Video) {
      return videoType
    }
    return null
  }
)
```

The problem is that video node is always null, even when actual video is being returned from the database, because for it to not be null I need to look it up based on id or somehow fetch it from database (which I am doing as you can see above).

This is the video node I am referring to:

```
video: {
  type: videoType,
  args: Object.assign(
    {},
    connectionArgs,
    {id: {type: GraphQLString}}
  ),
  resolve: (_, args) => {

    return docClient.query(
      Object.assign(
        {},
        {TableName: videosTable},
        {KeyConditionExpression: 'id = :id'},
        {ExpressionAttributeValues: { ':id': args.id }},
        paginationToParams(args)
      )
    ).promise().then(dataToConnection)

  }

},
```

I tried doing database query directly inside node definitions, but that didn't work (mostly because `storyType.interfaces` is `undefined` because `nodeDefs.nodeInterface` is not being passed through).

dataToConnection just converts the output of dynamoDB:
```
video DATA!!  { Items: 
   [ { id: 'f4623d92-3b48-4e1a-bfcc-01ff3c8cf754',
       url: 'http://www.pokkentournament.com/assets/img/characters/char-detail/detail-pikachuLibre.png',
       name: 'YAHOO' } ],
  Count: 1,
  ScannedCount: 1 }
```

into something that graphql relay understands:
```
video dataToConnection!!  { edges: 
   [ { cursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
       node: [Object] } ],
  pageInfo: 
   { startCursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
     endCursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
     hasPreviousPage: false,
     hasNextPage: false } }
```

and the function itself can be found here: https://github.com/dowjones/graphql-dynamodb-connections/pull/3/files

It is definitely NOT the problem here, but just FYI.

Also, asking/querying for id makes the whole video object null:

![image](https://cloud.githubusercontent.com/assets/3421858/22246375/8c26f4b6-e22c-11e6-8d1c-1034ee9dcf15.png)

But omitting id from the query returns something, whether querying with relay id:

![image](https://cloud.githubusercontent.com/assets/3421858/22246381/970f1282-e22c-11e6-9e3f-c8fbf9f000c2.png)

or database id

![image](https://cloud.githubusercontent.com/assets/3421858/22246387/9eee35be-e22c-11e6-827d-3a0696cae0f2.png)

and querying for all of the videos works:

![image](https://cloud.githubusercontent.com/assets/3421858/22246391/a8309694-e22c-11e6-87bb-8a64a7e441a5.png)

The interesting part is that I get exactly same problem even if I delete the video part from node definitions:

```
let nodeDefs = nodeDefinitions(
  (globalId) => {
    let type = fromGlobalId(globalId).type
    let id = fromGlobalId(globalId).id
    if (type === 'Store') {
      return store
    }
    return null
  },
  (obj) => {
    if (obj instanceof Store) {
      return storeType
    }
    return null
  }
)
```

even if I replace `return video` with `return 'bla'`, still nothing and all the console logs I put in there are ignored.

@wincent @dschafer @leebyron

**Comment by codepreneur** [comment]
I did some digging and found that interfaces in fact is `undefined`

```
const storeType = new GraphQLObjectType({
  name: 'Store',
  fields: () => ({
    id: globalIdField('Store'),

    allVideosConnection: {
      type: allVideosConnection.connectionType,
      args: Object.assign(
        {},
        connectionArgs
      ),
      resolve: (_, args) => {

        return docClient.scan(
          Object.assign(
            {},
            {TableName: pokemonTable},
            paginationToParams(args)
          )
        ).promise().then(dataToConnection)
      }
    },

    video: {
      type: videoType,
      args: Object.assign(
        {},
        connectionArgs,
        {id: {type: GraphQLString}}
      ),
      resolve: (_, args) => {

        return docClient.query(
          Object.assign(
            {},
            {TableName: pokemonTable},
            {KeyConditionExpression: 'id = :id'},
            {ExpressionAttributeValues: { ':id': args.id }},
            paginationToParams(args)
          )
        ).promise().then(dataToConnection)
        
      }
    
    }

  }),

  interfaces: [nodeDefs.nodeInterface]

})


```

```
console.dir(storeType.interfaces, { depth: null })

```
prints `undefined`

**Comment by codepreneur** [comment]
Some more digging:

![image](https://cloud.githubusercontent.com/assets/3421858/22253210/9b9357fc-e248-11e6-9fa4-706baee44d56.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/22253222/a6585034-e248-11e6-863a-73850c0575cb.png)

**Comment by mattecapu** [comment]
Do you have a definition for `videoType`? Could you craft a minimal example of the issue?

**Comment by codepreneur** [comment]
@mattecapu of course

```
const videoType = new GraphQLObjectType({
  name: 'Video',
  fields: () => ({
    id: {
      type: new GraphQLNonNull(GraphQLID),
      resolve: (obj) => obj.id
    },
    name: { type: GraphQLString },
    url: { type: GraphQLString }
  }),
  interfaces: [nodeDefs.nodeInterface]
})
```

**Comment by mattecapu** [comment]
The type definition explains why it only complains about `Video` being `null` when you explicitly ask for its `id` (you declared it non-null, while the other fields will happily return `null` as you can see from your tests).

Yet it still doesn't explain why you get a `null` object in the first place.

How do you pass around your node definitions interfaces? Do you have a separated module?

**Comment by codepreneur** [comment]
@mattecapu everything you see in here (all my code samples) are all in the same file.

**Comment by codepreneur** [comment]
This is what is being returned in `video: {}` resolve:

```
{ edges: 
   [ { cursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
       node: 
        { id: 'f4623d92-3b48-4e1a-bfcc-01ff3c8cf754',
          url: 'http://www.pokkentournament.com/assets/img/characters/char-detail/detail-pikachuLibre.png',
          name: 'YAHOO' } } ],
  pageInfo: 
   { startCursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
     endCursor: 'ZHluYW1vZGJjb25uZWN0aW9uOmY0NjIzZDkyLTNiNDgtNGUxYS1iZmNjLTAxZmYzYzhjZjc1NA==',
     hasPreviousPage: false,
     hasNextPage: false } }
```

Somehow that's okay for `allVideosConnection`, but not okay (ends up `null`) for `video`

Do I need to convert ids of nodes to global IDs? using `toGlobalId` ? Just for `video` ?

Because another thing I noticed is that if I 
```
console.log('fromGlobalId', fromGlobalId(globalId))
```
inside my node definitions, this query:

```
{
  node(id: "f4623d92-3b48-4e1a-bfcc-01ff3c8cf754") {
    id
    ...F1
  }
}

fragment F1 on Video {
  url
  name
}

```

becomes this:

```
fromGlobalId { type: '', id: '\u000e6]_v{vxsn\u001eU/\u001b}G>SW_]O\u001c>x' }
```

**Comment by codepreneur** [comment]
So to make node definitions work, all I had to do was this:

```
class Video {}
let video = new Video()
return Object.assign(video, data.Items[0])
```

i.e. create class with the same name as type name
and then `Object.assign` to it

Just doing this, doesn't work:
```
return {Video: data.Items[0]}
```

I also need to create IDs in the database like that: `Video:f4623d92-3b48-4e1a-bfcc-01ff3c8cf754`, where I am essentially putting `type` and randomly generated unique id together separated by a colon (`:`) and then encode it with `toGlobalId` function of `graphql-relay-js` library (so I end up with `VmlkZW86ZjQ2MjNkOTItM2I0OC00ZTFhLWJmY2MtMDFmZjNjOGNmNzU0Og==`), so then I can decode it with `fromGlobalId` so that `node definitions` can retrieve both `type` and `id`(`{ type: 'Video', id: 'f4623d92-3b48-4e1a-bfcc-01ff3c8cf754:' }`), after which I still need to add `fromGlobalId(globalId).id.replace(/\:$/, ''))` to remove the trailing colon (`:`).


Also, `interfaces` are not meant to be accessible, they are just for configuration.
