### ISSUE TITLE
What if i already have a Node object type? Can i rename relay's "Node" interface 

### ISSUE THREAD

**Issue by benjaminhon** [graphql/graphql-relay-js#150]
Due to historical reasons, we have an Object type called Node already along with node(id: String) query in our graphql server.

I would like to add relay now, but i realised that relay also uses the Node interface type, thus clashing with our Node object.

Is there anyway to rename relay's Node to RelayNode?

Thanks

**Comment by wincent** [comment]
If you update to Relay Modern (1.0.0 or above) you may be able to get pretty far. Relay no longer dynamically constructs `node` queries when refetching data (all queries are explicitly provided by the developer). It *does*, however, still assume that `Node` is an interface, and the compiler will try to add an `id` field when it encounters a type that implements `Node` ([see here](https://github.com/facebook/relay/blob/dbaa18af9c2067733cd7df470c0428f57c43a77f/packages/relay-compiler/transforms/RelayGenerateRequisiteFieldsTransform.js#L44)).

Having said that, I think there's a chance that this could work just fine even if you have a `Node` type (not an interface): I think the [`mayImplement` check](https://github.com/facebook/relay/blob/dbaa18af9c2067733cd7df470c0428f57c43a77f/packages/relay-compiler/graphql-compiler/core/GraphQLSchemaUtils.js#L65) just might fall through gracefully if it is not an interface.

So the answer to the question is: no, you cannot rename `Node` to `RelayNode`, but if you upgrade to Relay Modern then you might not need to (and if you run into any problems, then I would think that it would be reasonable for us to look at making changes or accepting PRs to allow that use case).
