### ISSUE TITLE
toGlobalId/fromGlobalId not working inside React Native

### ISSUE THREAD

**Issue by vincentisambart** [graphql/graphql-relay-js#152]
I tried using this library's `toGlobalId` and `fromGlobalId` from a React Native application, however I got an error that `Buffer` is not defined (it's used in [src/utils/base64.js](https://github.com/graphql/graphql-relay-js/blob/9496e3ff2caa5919cda175c8fddbfac743954727/src/utils/base64.js)). It seems that `Buffer` is only available from NodeJS...

If you consider that this library should also be available from React Native (or a browser), at least some changes need to be made to base64.js.

In the time being I'll probably just use join/split.

By the way, the reason I was trying to use this library from React Native is to do something similar to http://graphql.org/blog/rest-api-graphql-wrapper/.

**Comment by wincent** [comment]
Thanks for the report @vincentisambart.

> In the time being I'll probably just use join/split.

This is a reasonable approach. Note that the use of base64 encoding is a convention but not a requirement. The main reason we have used base64 historically is to make it clear that the identifiers should be considered opaque, and the client should avoid doing any operations that depend on their internal structure; in many (most?) cases you can write a client without needing the functionality of `toGlobalId`/`fromGlobalId` at all. (At the same time, base64 is an easily enough removed form of obfuscation that you can trivially undo if you need to look "inside" an ID for debugging purposes.)

**Comment by blackxored** [comment]
I ran into exactly the same issue. Any ways to make this cross-platform?

**Comment by sibelius** [comment]
@vincentisambart how did you solved your problem?

**Comment by sibelius** [comment]
You can create a simple helper

```jsx
import { Buffer } from 'buffer';

export type Base64String = string;

export function base64(i: string): Base64String {
  return new Buffer(i, 'utf8').toString('base64');
}

export const toGlobalId = (type: string, id: string): string => {
  return base64([type, id].join(':'));
};
```
