### ISSUE TITLE
Missing flow comment on index file

### ISSUE THREAD

**Issue by jamiehodge** [graphql/graphql-relay-js#154]
Flow types don't appear to be exporting from the top-level index:

`import { fromGlobalId } from 'graphql-relay'`

`fromGlobalId` is returned as the `empty` type.

Please add the missing `// @flow` comment, assuming there's nothing prohibiting doing so.

**Comment by jamiehodge** [comment]
I just noticed that the build is not exporting flow types at all. :(

**Comment by wincent** [comment]
v0.5.2 (just released) comes with Flow type definitions: https://github.com/graphql/graphql-relay-js/releases/tag/v0.5.2

**Comment by sibelius** [comment]
@wincent how can I setup my .flowconfig to make flow find `graphql-relay` type definitions (.js.flow files) ?

**Comment by sibelius** [comment]
figure it out

on .flowconfig
```
[libs]
node_modules/graphql-relay/lib/index.js.flow
```
