### ISSUE TITLE
Reusable inputs and payloads currently not possible w/ mutationWithClientMutationId?

### ISSUE THREAD

**Issue by unirey** [graphql/graphql-relay-js#156]
I read the code and it seems that it's currently not possible, am I right? Also, it doesn't seem to be possible to add other "root level arguments" to mutations, like `id` in example below.

_E.g:_

```graphql
input PostInput {
  title: String
  content: String
}

type Mutation {
  createPost(input: PostInput): Post
  updatePost(id: ID!, input: PostInput): Post
}
```

Should these be possible? What do you think? Same case w/ payloads.

If schema is mutation heavy, have lots of different types and each type has create / update or other similar mutations, duplicates waste a lot of resources. It hurts especially in situations where you need to spin up your bloated schemas regularly (_e.g_ fast growing serverless trends).

**Comment by davidrossjones** [comment]
I have the same question @adjourn . Is it possible to use GraphQLInputField with mutationWithClientMutationId?
