### ISSUE TITLE
ConnectionConfig nodeType

### ISSUE THREAD

**Issue by jamiehodge** [graphql/graphql-relay-js#160]
Is there anything prohibiting ConnectionConfig accepting a GraphQLInterfaceType for its nodeType?

https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L64

I will make a PR is there are no objections.

**Comment by frederik** [comment]
hey @jamiehodge. I just stumbled upon the same issue but with the Union Type.

Just allowing a UnionType has worked without any other changes for me in this scenario (but then I haven't explored this much).

If you make a pull request, I'd appreciate if you included the UnionType as well.
