### ISSUE TITLE
Many-to-many Link mutation Issue

### ISSUE THREAD

**Issue by awdDev786** [graphql/graphql-relay-js#163]
I am using <a href="https://github.com/graphql/graphql-relay-js">Graphql Relay</a> for applying connection model.I have scenario as teacher and student are having Many-to-Many relationship. My Link mutation code is as follows.:

       var teacherType = require('./teacherType.js')
       var officeType = require('./officeType.js')

        let LinkMutation = mutationWithClientMutationId({
    name: 'CreateLinkstudent',
    inputFields: {
        abc: { type: graphql.GraphQLBoolean }, 
        teacher:{type:new graphql.GraphQLList(teacherType.teacherInputType)},
        office:{type:officeType.officeInputType}
    },
    outputFields: {
        linkEdge: {
            type: Connection.edgeType
        },
        student: {
            type: ConType,
            resolve: () => entity
        }
    },
    mutateAndGetPayload: (args) => {
        //data saving code here
       }
     });

teacherType.js consists of teachertype and teacherInputtyp as follows:

       const teacherInputType = new graphql.GraphQLInputObjectType({
       name: 'teacherinput',
       fields: () => {
        var studentType = require('./studentType.js')
        return {
            _id: {
                type: graphql.GraphQLID
            },
            name: { type: graphql.GraphQLString },
            student: { type: new graphql.GraphQLList(studentType.studentInputType) },
        }
       }
    });

This gives error as 

       Can only create List of a GraphQLType but got: undefined.

and the reason is teacherType.js cannot be imported here.When i tries to change 

       teacher:{type:new graphql.GraphQLList(teacherType.teacherInputType)}

To this

      teacher:{type:teacherType.teacherInputType},

 error is:

     CreateLinkstudentInput.teacher field type must be Input Type but got: undefined

I got this error once when file with associated entity wasn't being loaded and i solved it by requiring it inside fields function of input type as i did in      teacherInputType  But here i cannot find the solution.

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
You should use Thunks for `inputFields`.
