### ISSUE TITLE
Feature: Allow a GraphQLObjectType to RUN mutate the payload object BEFORE resolving fields

### ISSUE THREAD

**Issue by jamesone** [graphql/graphql-relay-js#166]
I was thinking that it'd be cool if we were able to mutate the payload returned to a _GraphQLObjectType_ before resolving it's fields.

### Why?

In some instances, multiple fields may be required to run the _SAME_ bit of code. For example: an sql request.

Maybe I have something like:

```
const User = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  fields: () => ({
    friends: {
      type: GraphQLList(friend_type),
      resolve: user => < RUN SQL TO GRAB FRIENDS HERE >
    },
    friends_with_same_interests: {
      type: GraphQLList(friend_type),
      resolve: user => < RUN THE SAME SQL AS ABOVE TO GRAB FRIENDS AND THEN RUN IT THROUGH AN ALGORITHM TO FIND FRIENDS WHO HAVE THE SAME INTERESTS >
    },
    ....etc
```

If we added something that could mutate the payload, e.g:

```
const User = new GraphQLObjectType({
  name: 'User',
  description: 'A user',
  runBefore: (payload) => {
    const updatedPayload = payload;
    updatedPayload.friends = await < RUN SQL ONCE TO GRAB FRIENDS >;
    return updatedPayload;
  },
  fields: () => ({
  ... Now friends and friends_with_same_interests can access the same SQL results!
```

Is this explanation clear enough?

**Comment by wincent** [comment]
Have you looked into something like [DataLoader](https://github.com/facebook/dataloader)?

**Comment by jamesone** [comment]
Yeah I did know about Dataloader before posting this @wincent I thought that maybe it'd be a good addition to have this `runBefore` method, which would allow us to mutate the payload ourselves (it would be entirely up to us to return a valid payload & would just be another option to using Dataloader)? 

I don't think it'd be hard to implement this method in either? I would be able to take the time todo it myself (only if it's something you guys want) 😃 

I guess it would just be an option you could use without having to set up the Dataloader library. I would think that having a method like this would allow us to customise our types even more (giving us more control over the type).

Thoughts?

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
This issue is not specific to relay-style mutations and already discussed in `graphql-js` repo.
