### ISSUE TITLE
Add flow types common to relay specs

### ISSUE THREAD

**Issue by mike-marcacci** [graphql/graphql-relay-js#173]
It would be awesome if this library exported the types defined [here](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connectiontypes.js), since it would allow us to import them:

```js
import {
	connectionArgs,
	type ConnectionArguments,
} from 'graphql-relay';
```

...and do this in our graphql resolve functions:

```js
args: {
	...connectionArgs,
	custom: { type: GraphQLString }
},
resolve: async function (
	source: *,
	args: ConnectionArguments & {
		custom: string
	},
) {
	// ... DO SOMETHING HERE
}
```

**Comment by mike-marcacci** [comment]
This would be fixed by PR #174.

**Comment by sibelius** [comment]
this would be great

**Comment by kassens** [comment]
Will see if I can do a release tomorrow.

**Comment by mike-marcacci** [comment]
Awesome, thanks!

**Comment by jgcmarins** [comment]
this worked for me:
```
import type { Connection } from 'graphql-relay/lib/connection/connectiontypes';
```
