### ISSUE TITLE
Relicense under MIT

### ISSUE THREAD

**Issue by blaiprat** [graphql/graphql-relay-js#175]
Hi there 👋! 

Just wondering what's the status of relicensing this module under MIT. As of today, GraphQL and Relay has already been relicensed under MIT, but this module ties things together and still includes the PATENT license. 

Is this on the scope to be relicensed?

**Comment by wincent** [comment]
cc @leebyron who has been taking point on this stuff with our legal team.

**Comment by taion** [comment]
Ping!

**Comment by kassens** [comment]
1 month later, we can close this with 4fdadd3bbf3d5aaf66f1799be3e4eb010c115a4a!
