### ISSUE TITLE
Add subscriptionWithClientId

### ISSUE THREAD

**Issue by taion** [graphql/graphql-relay-js#182]
Should there be a `subscriptionWithClientId` here?

The shims we've been using to get subscriptions working with Relay Classic end up requiring a `clientSubscriptionId` by analogy with `clientMutationId`.

However, the Relay Modern subscription example doesn't document the same "single-input-with-client-ID" pattern as for mutations. Compare:
- Subscriptions: https://facebook.github.io/relay/docs/subscriptions.html
- Mutations: https://facebook.github.io/relay/docs/mutations.html

I've implemented all of this already in https://github.com/taion/graphql-relay-subscription/blob/v0.2.0/src/index.js, but I'm not sure if this is just random legacy stuff that I'm keeping around just for Relay Classic, that I should look to remove once I'm fully on Relay Modern.

**Comment by sibelius** [comment]
@kassens would you accept a PR adding subscriptionWithClientId?

based on this one https://github.com/taion/graphql-relay-subscription/blob/v0.2.0/src/index.js#L13?

**Comment by taion** [comment]
It might be unnecessary now for Relay Modern?

**Comment by kassens** [comment]
Yeah, this is an artifact from Relay Classic that we no longer need.

**Comment by sibelius** [comment]
It provides a good pattern
