### ISSUE TITLE
Documentation for `ConnectionConfig`

### ISSUE THREAD

**Issue by damassi** [graphql/graphql-relay-js#184]
It would be nice if there was some documentation around `ConnectionConfig`. While working with `connectionDefinitions` I only noticed that `connectionFields` was available by digging into the [type definitions](https://github.com/graphql/graphql-relay-js/blob/373f2dab5fc6d4ac4cf6394aa94cbebd8cb64650/src/connection/connection.js#L62).

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
We planning to move this library into graphql-js and use JSDoc comment we already have to generate documentation.
So this issue should resolve itself after we achieve this goal.
