### ISSUE TITLE
Mutation code breaks if method returns void.

### ISSUE THREAD

**Issue by aatifhussain** [graphql/graphql-relay-js#186]
https://github.com/graphql/graphql-relay-js/blob/481cae9ef6c0eb33849915caac21398307d9be54/src/mutation/mutation.js#L107

I am using loopback-graphql-relay package in my project. There are few loopback methods that don't return anything. For those methods graphql-relay's code break.

Below is the example mutation.

`mutation {
  User {
    UserResetPassword (input:{options:{email:"user@example.com"}}) {
      obj 
      clientMutationId
    }
  }
}
`

**Comment by IvanGoncharov** [comment]
Fixed by #268
