### ISSUE TITLE
Documentation/Link broken https://facebook.github.io/relay/docs/graphql-relay-specification.html 

### ISSUE THREAD

**Issue by sagar-ganatra** [graphql/graphql-relay-js#196]
The link to get the GraphQL server specification is broken - https://facebook.github.io/relay/docs/graphql-relay-specification.html

**Comment by sagar-ganatra** [comment]
Found out that the link should have been - https://facebook.github.io/relay/docs/en/graphql-server-specification.html 
CMIIW

**Comment by IvanGoncharov** [comment]
Already fixed
