### ISSUE TITLE
There's no documentation about connectionFromArraySlice

### ISSUE THREAD

**Issue by erickbelfy** [graphql/graphql-relay-js#199]
Hi everyone i was just reading the GitHub repo but i couldn't find the documentation of `connectionFromArraySlice`, i know what it does and its param signature (because I saw on StackOverflow) but there's nothing here. 

If there's not documentation related i can work on it, but first i want to be sure :D

Thanks!

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
We planning to move this library into `graphql-js` and use JSDoc comment we already have to generate documentation.
So this issue should resolve itself after we achieve this goal.
