### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers/extends'

### ISSUE THREAD

**Issue by oguzbilgic** [graphql/graphql-relay-js#2]
I may be doing something wrong, however as soon as I import 'graphql-relay' package I get the following error.

Thank you.

**Comment by dschafer** [comment]
Hm, I'm not able to reproduce, just tried a fresh clone + install + test. Can you describe the sequence of commands you ran that led to that error?

**Comment by oguzbilgic** [comment]
I was extracting a fresh repo (from the project) to demonstrate the issue. However deleting the `node_modules/` and reinstalling all the dependencies fixed the issue. I will let you know if I can reproduce. Thank you.
