### ISSUE TITLE
Publish ESM (.mjs) entry point to npm

### ISSUE THREAD

**Issue by motiz88** [graphql/graphql-relay-js#208]
While working on optimising the bundling of https://github.com/graphql/swapi-graphql — for _reasons_<sup>1</sup> — I discovered that it was `import`ing things from `graphql-relay-js`, but that the latter, unlike `graphql-js`, only had a CommonJS entry point published to npm.

It might be desirable to add an ES module build target to this package, modeled on what `graphql-js` is [already doing](https://github.com/graphql/graphql-js/blob/54f631ff3238affdddb4dc736fc282b620d70b15/package.json#L37).

---

<sup>1</sup> See https://twitter.com/motiz88/status/985110696668131328 - I'm investigating the [claim](https://github.com/apollographql/apollo-link/blob/a2025ad5a2eb7a1164d61a402e5deb227e14a84f/packages/apollo-link-schema/README.md) that schema execution on the front-end is impractical due to `graphql-js`'s [footprint](https://bundlephobia.com/result?p=graphql) in terms of bundle size. `swapi-graphql` simply happens to be a good, accessible testbed for just that (thanks @IvanGoncharov for the tip! 🙏)

**Comment by motiz88** [comment]
I've pretty much completed this at https://github.com/motiz88/graphql-relay-js/commits/publish-mjs but hit https://github.com/webpack/webpack/issues/7032 due to the use of `Buffer` etc. Looking for viable workarounds. (Potentially this can still go ahead as it's technically a Webpack bug.)

**Comment by IvanGoncharov** [comment]
Sorry for the long delay.
We plan to merge this lib into graphql-js to provide the better maintenance and attention it deserves.
This should happen over the next few months and so closing this since graphql-js already provides mjs files.
