### ISSUE TITLE
Translating cursors to original object id's

### ISSUE THREAD

**Issue by indiloop** [graphql/graphql-relay-js#21]
Hey guys,

I was wondering if anyone could shed some light on how edge cursors work, and how they are generated.

I am trying to leverage the paging functionality provided by "connections", but I am not sure whether my cursors are being generated properly. At first I thought a cursor was the global id of the edge object, which I could have converted in its original id using fromGlobalId(args.after) but it seems that isn't the case. 

I need to get at the original id, so that i can structure my SQL query to only retrieve results that occur after my original id. My sql database has no knowledge of the cursors generated in graphql, so I'm at a loss on how to make that connection.

Thanks in advance!

**Comment by dschafer** [comment]
Each connection can create cursors in whatever shape it deems appropriate. The example in `relay-graphql-js`, `arrayFromConnection`, creates a connection out of an array, so the only data it needs in the cursor is the offset into the array. Hence, at https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L33, we just call `offsetToCursor` at https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L106, which creates the "cursor string" (it's just simple transform atop the offset, designed to make it clear to the client that the cursor is opaque).

You can build a connection without `arrayFromConnection`, which might be appropriate in cases where the connection is not backed by an array, but by something like a SQL table. In that case, you can define your cursors to contain whatever information you'll need to continue pagination.

**Comment by indiloop** [comment]
Cool, thanks for the quick reply. This makes a lot more sense to me now. I was essentially trying to use the connectionFromArray function as an intermediary from my database. I didn't realize it was purely meant to operate on a fixed size array. 

Cheers!
