### ISSUE TITLE
Add clarifications about edge order to the relay cursor connections specification

### ISSUE THREAD

**Issue by jedwards1211** [graphql/graphql-relay-js#212]
I'm not sure where the repo for the specification webpage lives.  Hopefully this is the right place for this issue?

Recently while working on improving `graphql-sequelize`'s implementation of connections, I discovered that, as far as I understand, someone misinterpreted the specification: their implementation returns `edges` in the opposite order when the `last` argument is used.  This also means the `startCursor` and `endCursor` are swapped, and their reverse pagination test fetches the previous page by requesting `last: 3, before: pageInfo.endCursor`.  But as far as I understand `before` should always take the `startCursor` of the current `pageInfo`.

I've submitted a PR to fix their implementation but I'd also like to help prevent this kind of misinterpretation for anyone in the future.

Adding the following clarifications to the Relay Cursor Connections Specification would precisely specify the ordering of `edges`:
* The ordering of `edges` should be the same when using `first/after` as when using `last/before`, all other arguments being equal
* To fetch the next page one should use `after: pageInfo.endCursor`, not `after: pageInfo.startCursor`
* To fetch the previous page one should use `before: pageInfo.startCursor`, not `before: pageInfo.endCursor`
* When `before: cursor` is used, the edge closest to `cursor` should come **last** in the result `edges`.
* When `after: cursor` is used, the edge closest to `cursor` should come **first** in the result `edges`.

**Comment by jedwards1211** [comment]
Okay this needs to go in `facebook/relay`, I'll move it there.

**Comment by yvele** [comment]
For people coming from Google, the issue moved here https://github.com/facebook/relay/issues/2466

**Comment by jedwards1211** [comment]
@yvele ah thanks, sorry I forgot to do that!
