### ISSUE TITLE
asynchronous nodeDefinitions?

### ISSUE THREAD

**Issue by tanekim77** [graphql/graphql-relay-js#213]
I am trying to get nodeDefinitions work asynchronously. Does this work? According to the definition of nodeDefinitions function, it does not seem it is designed to return a promise.  But would await nodeDefinitions work?
How do people resolve this issue, when database is fetched asynchronously, like await db.findOne({ id });?

```
const { nodeInterface, nodeField } =  await nodeDefinitions(
    async (globalId) => {
     const { type, id } = fromGlobalId(globalId);
     const foundEntity = await db.findOne({ id });
     // return {id}
     return foundEntity;
   },
   (obj) => {
      return GraphQLUser;
   },
 );
```

**Comment by sibelius** [comment]
Use idFetcher, check code
