### ISSUE TITLE
mutationWithClientMutationId should accepts a thunk as outputFilelds

### ISSUE THREAD

**Issue by davide-ganito** [graphql/graphql-relay-js#22]
Hi everyone,
I think that mutationWithClientMutationId should accepts also a thunk as outputFilelds.
I need to create payloads with type which are not ready at definition time.

**Comment by dschafer** [comment]
Yep, good idea; it should take either a thunk or an array!

**Comment by dschafer** [comment]
> Yep, good idea; it should take either a thunk or an array!

I meant thunk or object. Too much time in PHP!

**Comment by dschafer** [comment]
Should be fixed by #26.
