### ISSUE TITLE
mutationWithClientMutationId - how to nest mutations?

### ISSUE THREAD

**Issue by tvedtorama** [graphql/graphql-relay-js#226]
I want to set up nested mutations where the output of the parent are needed as input to the children.  However I find the `source` value in the resolver to be ignored by relay in `mutationWithClientMutationId`.

This field contains the "nesting context" for my nested mutation, ie the the output from the parent mutation.

From the source, with the underscore representing the wanted "context":

```javascript
resolve: (_, {input}, context, info) => {
      return Promise.resolve(mutateAndGetPayload(input, context, info)).then(
        payload => {
          payload.clientMutationId = input.clientMutationId;
          return payload;
        }
      );
    },
 ```

I have been searching all over the internet to find other ways to pass the "nesting context", such as by augmenting the GraphQL context - but cant find any.   Are there any other recommended ways to support nested mutations with Relay?

**Comment by jgcmarins** [comment]
@tvedtorama, I can't find a context for `nested mutations`. It looks like it's something out of the standards.
What I recommend you to do is to think about mutations as `atomic actions`.
Instead of trying to call a mutation `inside` another mutation, why don't you call a mutation `after` another mutation?

**Comment by tvedtorama** [comment]
You are right that this is not the most common thing, and not a nicely atomic affair.

I need it for a quick and intuitive way to build recursive structures - where the `id` of the parent becomes the `parentId` of the nested child. 

This could also be handling by making the mutation and payload support the recursive structure, but for the moment that did not seem like the best option. 

It works perfectly when the source is allowed to pass into `mutateAndGetPayLoad’. 

Here’s an article with some ideas on nesting: 

https://medium.freecodecamp.org/beware-of-graphql-nested-mutations-9cdb84e062b5

https://hackernoon.com/graphql-nested-mutations-with-apollo-small-fatigue-max-gain-1020f627ea2e

**Comment by jgcmarins** [comment]
Got it!
Thanks for the resources :)

**Comment by IvanGoncharov** [comment]
the nested mutation is not something that is supported by GraphQL specification.
