### ISSUE TITLE
Difficult to use connectionFields

### ISSUE THREAD

**Issue by KyleAMathews** [graphql/graphql-relay-js#23]
When resolving a connectionType, it'd be nice if you could pass optional information back to custom `connectionFields` defined within `customDefinitions`.

I'm working on a search connection type atm and I want to be able to set as connection fields `total` and `took` (the search time). Those would necessarily only be known within the `searchConnection` `resolve` function.

If given some guidance on a solution, I can put together a PR tomorrow.

**Comment by dschafer** [comment]
Hm, seems like https://github.com/graphql/swapi-graphql/blob/master/swapi/src/schema/connections.js#L40 does something similar, does that approach work for you?

**Comment by KyleAMathews** [comment]
Ooo... that led me to this: https://github.com/graphql/swapi-graphql/blob/ba3f82aa27115ef7c095a2a96023c58ca367beef/swapi/src/schema/connections.js#L76-L79

Reading that helped make click that I just needed to return an object in the shape expected by `connectionType`. So similar to the code above I merged the results of `connectionFromArray` with the custom `connectionFields` I'm using.

```coffeescript
new Promise((resolve, reject) ->
  hits = index.search args.query

  # Hydrate
  async.map hits, ((hit, cb) ->
    postsByIdDb.get(hit.ref, (err, value) ->
      if err
        return cb(err)
      else
        cb(null, value)
    )
  ), (err, hits) ->
    if err
      reject err
    else
      resolve assign(
        connectionFromArray(hits, args),
        {
          total: hits.length
          took: process.hrtime(start)[1] / 1000000
        }
      )
)
```

**Comment by grydstedt** [comment]
I'm dealing with something similar. I've added custom fields to the connectionFields. This works great on the first retrieval, but when I refetch via `setVariables` (and increase number of items to fetch) these custom fields are not included in the request. I'd like to get a new `rangeBegin` and `rangeBegin` on each query here:

```
var PackagesRelay = Relay.createContainer(PackagesBase, {
  initialVariables: {
    first: PAGE_SIZE,
	filter: {}
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on Viewer {
        packages(first: $first, filter: $filter) {
          ${PackageListing.getFragment('packages')}
          totalCount
          rangeBegin
          rangeEnd
          pageInfo {
            hasNextPage
          }
        }
      }
    `
  }
});
```

**Comment by sibelius** [comment]
@grydstedt could u post an example of how u did totalCount?
