### ISSUE TITLE
Relay mutationWithClientMutationId does not pass forward the "extensions" field

### ISSUE THREAD

**Issue by JCMais** [graphql/graphql-relay-js#244]
Looking at the code for `mutationWithClientMutationId` the `extensions` field is not passed forward: https://github.com/graphql/graphql-relay-js/blob/84ed0008ee17ae439ce67d820a29d1f258addff8/src/mutation/mutation.js#L68-L75

The new `extensions` field was added on the following commit https://github.com/graphql/graphql-js/pull/2097 and it's available since GraphQL v14.5.0, this new field is the recommended way to add metadata to GraphQL fields.

**Comment by jgcmarins** [comment]
related #245
