### ISSUE TITLE
Support graphql v15

### ISSUE THREAD

**Issue by rigelglen** [graphql/graphql-relay-js#245]
Hi, `graphql-relay` currently does not include graphql 15.0 as a supported peer depenency. Even though graphql 15 came with some breaking changes, I don't think anything needs to be changed to support it.

**Comment by glen-84** [comment]
#242

**Comment by hehex9** [comment]
Any plans to release a new version?

**Comment by IvanGoncharov** [comment]
It's planned, see #292 for details
