### ISSUE TITLE
cursorForObjectInConnection uses indexOf method

### ISSUE THREAD

**Issue by almasakchabayev** [graphql/graphql-relay-js#29]
Array.indexOf is not very flexible and if I am retrieving item and array separately from a db, I have to manually find an element in an array to pass it into cursorForObjectInConnection.
Wouldn't it be more appropriate to use findIndex or isEqual from Lo-Dash?

**Comment by wincent** [comment]
I don't think we'd want to add a dependency on lodash, as we've intentionally kept the dependency footprint small (note that we only depend on `babel-runtime`).

If you can provide a bit more detail about what you're trying to achieve, and maybe some sample code, we could suggest ways to make it easier to do what you want.

**Comment by almasakchabayev** [comment]
Ok. I will explain what I was trying to do: Suppose I have list of items. I want to make a RANGE_ADD mutation. In mutateAndGetPayload function I receive inputs and save new Item to db, then I return this item: 
```
mutateAndGetPayload: async (input, { rootValue }) => {
    const item = new Item({
      text: input.text,
    });
    await item.save();
    return { item };
  },
```
In outputFields resolve function I fetch previously fetched items
```
outputFields: {
    itemEdge: {
      type: ItemEdgeType,
      resolve: async ({ item }) => {
        const array = await ItemModel.orderBy(...);
        ....
```
Here I want to return 
```
return {
          cursor: cursorForObjectInConnection(array, item),
          node: item,
        };
```
however cursorForObjectInConnection has indexOf in place, so it returns null, as item saved in mutateAndGetPayload is not the same object as the item in array, although they have exactly same properties and values.

So I have to manually find this Item in array to pass it to cursorForObjectInConnection, i.e.
```
outputFields: {
    itemEdge: {
      type: ItemEdgeType,
      resolve: async ({ item }) => {
        const array = await ItemModel.orderBy(...);
        let itemToPass;
        for (const i of array) {
          if (i.id === item.id) {
            itemToPass = item;
          }
        }
        return {
          cursor: cursorForObjectInConnection(array, itemToPass),
          node: itemToPass,
        };
```

Ugh.. It's not a big deal, I just don't like how the code looks

**Comment by bmcmahen** [comment]
I have the same problem. Perhaps an optional callback to provide our own equality conditions would suffice, or simply a third argument to specify the index of the matching node. I think the main problem is moreso silent failure when the `nodeList` and `node` come from two separate sources.

**Comment by athibaud** [comment]
i've had this problem myself... indeed it mostly arrises when nodeList and node come from seperate sources therefore the objects are equal in value but not in reference.. so `indexOf`fails.

plus it's a real pity to have to pass trough the list twice (once to find our node in the nodeList and once again in `cursorForObjecttInConnection` with `indexOf` to find the index of that node in the same nodeList...)

@bmcmahen's callback solution seems reasonable but seeing all `cursorForObjecttInConnection` does is return [offsetToCursor(index)](https://github.com/graphql/graphql-relay-js/blob/8f0fc3b/src/connection/arrayconnection.js#L167) wouldn't it be simpler to just expose `offsetToCursor` and let the user deal with finding the index ?

**Comment by wincent** [comment]
@athibaud:

> wouldn't it be simpler to just expose `offsetToCursor` and let the user deal with finding the index

I'd be ok with this, especially seeing as its inverse, `cursorToOffset`, is already exposed.

@bmcmahen, @almasakchabayev: Would that address your use case?

**Comment by bmcmahen** [comment]
Yup, that sounds good to me.

**Comment by athibaud** [comment]
@wincent :+1:

**Comment by almasakchabayev** [comment]
@wincent that solves the problem
