### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by andrehsu** [graphql/graphql-relay-js#292]
@kassens, is there a plan to release a new version of this library? There has been around 50 commits since the last release on January 2019. Specifically, I want to submit a PR to fix some of the types, am I'm not sure if I should submit it to @types/graphql-relay, or the yet-unreleased ones in this repo.

**Comment by IvanGoncharov** [comment]
@andrehsu Thanks for raising this issue 👍 
Just got right to the NPM package so now I'm able to release a new version.
Will work on the release tomorrow (update deps + fix `npm install` + merge PRs) and release.

P.S. Long term plan is to merge this package into https://github.com/graphql/graphql-js and we will probably do it this summer as part of GSoC: https://github.com/graphql/foundation/tree/main/mentorship/2021/gsoc#2-integrate-graphql-relay-js-into-graphql-jsmedium

**Comment by IvanGoncharov** [comment]
I don't forget about this issue, just catch COVID so very hard concentrate because of fewer.
It's at the top of my list once I start feeling better.

**Comment by camoedo** [comment]
HI @IvanGoncharov, any news about this merge?

**Comment by dcrdev** [comment]
Yes any news?

**Comment by IvanGoncharov** [comment]
Just released a new version https://github.com/graphql/graphql-relay-js/releases/tag/v0.7.0
