### ISSUE TITLE
Return type check problem of mutationWithClientMutationId after 0.7.0 update

### ISSUE THREAD

**Issue by gtolarc** [graphql/graphql-relay-js#339]
After the 0.7.0 update, the following code has a problem.
```javascript
const testMutation = mutationWithClientMutationId({
  name: 'TEST',
  inputFields: {
    name: { type: new GraphQLNonNull(GraphQLString) },
  },
  outputFields: {
    obj: {
      type, // some type
      resolve: (source, args, context, info) => source,
    },
  },
  mutateAndGetPayload: async (input, context, info) => {
    return new GraphQLError('TEST Error');
  },
}
```
Perhaps because the type defined in the output is forcibly checked, the error message return that was allowed in the past does not work. Is this the intended situation?

**Comment by IvanGoncharov** [comment]
@gtolarc Thanks for reporting 👍 
To confirm you get the error during type check and not in runtime, right?
Do you use Flow or Typescript?
Can you please paste the error message here?

**Comment by gtolarc** [comment]
<img width="999" alt="스크린샷 2021-06-21 오후 12 46 03" src="https://user-images.githubusercontent.com/8623798/122704439-b479c400-d28e-11eb-85e3-3079b93ea242.png">

I used typescript and this is an error that occurs at runtime.

**Comment by IvanGoncharov** [comment]
@gtolarc Thanks for reporting, fixed in https://github.com/graphql/graphql-relay-js/releases/tag/v0.8.0
