### ISSUE TITLE
Is the peer dependency on graphql exactly 15.5.1 on purpose?

### ISSUE THREAD

**Issue by badrange** [graphql/graphql-relay-js#355]
I noticed that the peer dependency on graphql was changed from `^15.5.0` to `15.5.0` in #350. Was the change from depending on a minor release to an exact patch release done on purpose?

If I install graphql-relay to a project which already has the most recent version of graphql installed it will require me to downgrade to an older graphql version that is depending on another project that has a security release.

**Comment by saihaj** [comment]
I think only major version should be locked for peer deps to avoid this issue. I have opened a PR will try to get a release out soon. cc @IvanGoncharov

**Comment by oliversalzburg** [comment]
I've been wondering about this as well. It forces us into an overly specific set of outdated dependencies for apparently no good reason.

**Comment by badrange** [comment]
Thank you for the quick reaction! :+1:
