### ISSUE TITLE
0.10.0 has no Flow type support

### ISSUE THREAD

**Issue by w01fgang** [graphql/graphql-relay-js#384]
Updating to 0.10.0 causes Flow errors as this version contains no type definitions for Flow. 😢
We use Flow type instead of TS in all our projects and we don't plan to switch to TS in near future.

**Comment by saihaj** [comment]
Hey! [Flow support](https://github.com/graphql/graphql-js/issues/2832) for `graphql-js` was dropped and to support `v16` here the Flow support was dropped.

**Comment by w01fgang** [comment]
So, no Flow types will be ever provided?

**Comment by saihaj** [comment]
If you wish to help maintain can add them to https://github.com/flow-typed/flow-typed Providing part of this project is also a possibility

**Comment by w01fgang** [comment]
Ok, got it. Thanks for the lightning-fast reply!
