### ISSUE TITLE
`node` type should not be restricted to `ObjectType`

### ISSUE THREAD

**Issue by OlegIlyenko** [graphql/graphql-relay-js#41]
Based on the `ConnectionConfig`, node type is required to be a `GraphQLObjectType`:

https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L62

But according to the spec:

> An “Edge Type” must contain a field called node. This field must return either a Scalar, Enum, Object, Interface, Union, or a Non‐Null wrapper around one of those types. Notably, this field cannot return a list.

https://facebook.github.io/relay/graphql/connections.htm#sec-Node

Is it a bug, or did I misunderstood the spec?

**Comment by dschafer** [comment]
Hm, I feel like you should be able to build connections to things other than object types; @yuzhi, thoughts?

**Comment by yuzhi** [comment]
Relay currently does not support connection/pagination properly if the node is not an object. Relay does support List of objects or scalars. What's the specific use case?

**Comment by OlegIlyenko** [comment]
I think the main use-case is to be able to use interface and union types. Also the way it is defined now in the reference implementation implies that `nodeType` is always nullable. I wonder whether this is intentional?

My main motivation though is that I implemented the same kind of behaviour in [sangria-relay](https://github.com/sangria-graphql/sangria-relay) previousely and in this particular place it contradicts the spec, so I get questions about it. People also ask whether it is possible to have an interface `nodeType`.

**Comment by dwhitney** [comment]
Hi, it makes sense to me not to restrict the node's type to ObjectType. Imagine I wanted to serve a list of mammals in a Connection, where some are dogs and some are cats. It makes sense in this case that my nodes are in InterfaceType and not an ObjectType. Without using InterfaceType as I've described, you have to create an ObjectType that bridges the functionality I want -- basically I create an ObjectType that has a field that is an InterfaceType that contains my mammal. It works, but it feels like a hack.

**Comment by nemanja-stanarevic** [comment]
@yuzhi @dwhitney @dschafer Should be able to have union and scalar/enum as connection nodes as well, right?  Specifically, relay/graphql spec indicates that the node field could be *"Scalar, Enum, Object, Interface, Union, or a Non‐Null wrapper around one of those types"* [1]

[1] https://facebook.github.io/relay/graphql/connections.htm#sec-Node

**Comment by amsayk** [comment]
@dwhitney Hi, I have a similar problem, and I tried the solution you proposed using an ObjectType that has a field that is an InterfaceType as my connectionType. However, I still couldn't get it to work.

Here is the error am getting:

"RelayQueryField: Range behavior keys are associated exclusively with connection fields. `getRangeBehaviorKey()` was called on the non-connection field `%s`."

Do you have any idea what I am missing? Thanks.

**Comment by itajaja** [comment]
just tested this client side, Relay (at least latest version) is happy with a connection of enums, and probably of interfaces too. I think the signature should change

**Comment by IvanGoncharov** [comment]
Fixed in #331
