### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by skevy** [graphql/graphql-relay-js#53]
Hi guys!

I noticed that there's been a ton of commits since Nov 2 (the last release)...a lot of them are super useful!

Could you release a new version to npm? Currently I'm having to install this from Sinopia...but I'd like to go back to npm.

Thanks!
-Adam

**Comment by dschafer** [comment]
Good call, just pushed 0.3.6! Release notes are at https://github.com/graphql/graphql-relay-js/releases/tag/v0.3.6.

**Comment by skevy** [comment]
Thanks @dschafer :)

**Comment by KyleAMathews** [comment]
Thanks Dan!
