### ISSUE TITLE
Common to be needing fromGlobalId in mutateAndGetPayload?

### ISSUE THREAD

**Issue by ryancole** [graphql/graphql-relay-js#59]
I'm slowly learning my way around Relay, and have written a few mutations so far with great success. None of my prior mutations have modified an existing record, though, so I don't have an example yet where I specify the id of something I'd like to update.

The mutation I'm currently working on will do just that, finally. I'm wanting to update an existing record. My mutation expects the id of the record as an argument. Coming from Relay, this is a globally unique id created with `toGlobalId`, though. So, within `mutateAndGetPayload` I've got access to that global id, which I figure I need to use `fromGlobalId` to get my local SQL primary key value.

Is this the typical use case? I need to code in a type check for this id to make sure it's of the right type, etc? Or is there a way to say that the id parameter needs to be the same type as the id on my other type, and it'll do that `fromGlobalId` for me?

Here's my mutation ...

```js
import {mutationWithClientMutationId} from "graphql-relay";
import {GraphQLID, GraphQLNonNull} from "graphql";
import AccountType from "../type/AccountType";
import TeamInviteType from "../type/TeamInviteType";
import * as AccountSql from "../../data/query/sql/account";
import * as TeamInviteSql from "../../data/query/sql/team-invite";

export default mutationWithClientMutationId({
  name: "AcceptTeamInvite",
  inputFields: {
    id: {
      type: new GraphQLNonNull(GraphQLID),
      description: "The id of the team invite."
    }
  },
  outputFields: {
    invite: {
      type: new GraphQLNonNull(TeamInviteType),
      resolve: source => source
    },
    account: {
      type: new GraphQLNonNull(AccountType),
      resolve: source => AccountSql.getById(source.account)
    }
  },
  mutateAndGetPayload: async (source, info) => {
    const {user} = info.rootValue;
    if (!user) {
      return Error("not allowed");
    }
    const invite = await TeamInviteSql.getById(source.id);
    if (user.id !== invite.account) {
      return Error("not allowed");
    }
    return TeamInviteSql.accept(invite.id);
  }
});
```

**Comment by dschafer** [comment]
> Is this the typical use case 

Yeah, this seems right to me; you get a global ID from the user, use `fromGlobalId` to get the type and the local ID, and then operate from there!

> Or is there a way to say that the id parameter needs to be the same type as the id on my other type, and it'll do that fromGlobalId for me?

There's nothing to do this automatically in `graphql-relay-js`. In terms of type hinting, I'd probably ensure the `GraphQLID` is used to mean global IDs everywhere.
