### ISSUE TITLE
invalid node ids when inputs contain non-ascii characters

### ISSUE THREAD

**Issue by josephsavona** [graphql/graphql-relay-js#62]
From facebook/relay/issues/755:

> Is there a reason why you user ascii as encoding and decoding base64 ids ? I got bitten by this as i had a swedish character in an id and was incorrectly encoded. Changed ascii to utf-8 in graphql-relay\lib\utils\base64.js and it worked.

cc @quazzie

**Comment by wincent** [comment]
Merged #90, so closing this one out.
