### ISSUE TITLE
mutationWithClientMutationId stripes description field

### ISSUE THREAD

**Issue by vinerz** [graphql/graphql-relay-js#65]
I am trying to define a new mutation with a description:

``` js
const createNode = mutationWithClientMutationId({
    name: 'createNode',
    description: 'Creates a new node in the system',

    inputFields,
    outputFields
});
```

As I can see in the source code, it is not possible to provide a description field to the mutation.
Is this behavior correct?

**Comment by chentsulin** [comment]
this could be close by #61

**Comment by JCMais** [comment]
I suppose this issue can be closed.
