### ISSUE TITLE
Evaluate the interfaces field lazily (if defined as a thunk)

### ISSUE THREAD

**Issue by kamek-pf** [graphql/graphql-relay-js#66]
Sharing `nodeInterface` across the different GraphQL types in a splitted  schema can lead to weird circular dependency issues.

Considering the fact that the different `field` types (in `mutationWithClientMutationId` or `GraphQLObjectType`) are evaluated lazily when defined as thunks, could we make it so the `interfaces` field is also evaluated lazily when defined as a thunk ?

Currently, it's evaluated immediately no matter how it is defined, which is not the expected behavior.

**Comment by dschafer** [comment]
@leebyron, thoughts? This would probably be a change to https://github.com/graphql/graphql-js

**Comment by wincent** [comment]
The thunk idea sounds reasonable on the surface.

As a workaround in the meantime @kamek-pf, you have a couple of options. One is just keeping everything that implements the interface in a single file (not great, obviously). The other: in a side project I ended up using [a registration pattern](https://github.com/wincent/masochist/blob/master/app/src/server/schema/definitions/node.js) to avoid the circular dependency issues.

**Comment by kevinSuttle** [comment]
I think this is something that GraphQL-JS needs to address. I got stuck on a circular dependency the very first time I tried to implement an `Interface`. Perhaps it's a doc issue? There is currently _very_ little documentation, and what's there is super confusing. 

https://facebook.github.io/graphql/#sec-Interface-type-validation

> The fields of an Interface type must have unique names within that Interface type; no two fields may share the same name.

Uh?

**Comment by kevinSuttle** [comment]
@leebyron Would love to hear your thoughts on this, because it's both a GraphQL _and_ a JavaScript issue, meaning, as soon as you try to circumvent the circular dependency by putting imports into your `resolveType:` function, you get a syntax error in ES6.

**Comment by c0d0g3n** [comment]
@kamek-pf and all others that stumble upon this issue: **You can now define interfaces as a thunk**. It worked for me (using  `graphql@0.10.5`  and `graphql-relay@0.5.2`) and [`swapi-graphql` is using it too](https://github.com/graphql/swapi-graphql/blob/master/src/schema/types/person.js#L113).

Hope this saves some people some searching :)
