### ISSUE TITLE
clarify install instructions in README

### ISSUE THREAD

**Issue by tjwebb** [graphql/graphql-relay-js#70]
see: https://github.com/graphql/graphql-relay-js#using-relay-library-for-graphqljs

The install line should more helpfully read:

```sh
npm install graphql graphql-relay
```

since the `graphql` module is a peer dependency. npm3 no longer installs peerDependencies by default

**Comment by wincent** [comment]
Good call. Would you like to submit a PR for this?

**Comment by wincent** [comment]
Doing a bit of spring cleaning, so pushed the suggested change myself. Thanks once again.
