### ISSUE TITLE
bump minor version after upgrading graphql peer-dependency

### ISSUE THREAD

**Issue by ringzhz** [graphql/graphql-relay-js#76]
Looks like you've already updated package.json to have a peer dependency on the latest version of graphql@0.5.0.
Can you please do a 0.3.7 release so consumers can run the latest version of the graphql lib while satisfying your peer-dependency?

**Comment by wincent** [comment]
Yes. See https://github.com/graphql/graphql-relay-js/pull/75

**Comment by wincent** [comment]
Release is [now up](https://www.npmjs.com/package/graphql-relay).

**Comment by ringzhz** [comment]
Thanks, @wincent.
