### ISSUE TITLE
Naming suggestions: PagedAssocation, Items, Item

### ISSUE THREAD

**Issue by mhart** [graphql/graphql-relay-js#8]
You're gonna hate this one :smile_cat:

I know, I know, naming things, etc. But I'd be remiss if I didn't at least make some suggestions.

So, I think Connections could be called PagedAssociations – or something along those lines. I feel like Connection has a very network/database connotation to it, and it makes it quite confusing for newcomers approaching a library that does actually deal with both network connections and probably database connections too – especially because they're being defined in the schema alongside database resolving functions.

I also think `edges` and `node` would perhaps be a little more newbie friendly if they were just `items` and `item`.

**Comment by tomatau** [comment]
+1 for Associations, this makes the relationship much clearer. Although association has a connotation with organisations/groups of people. So I'd like to suggest - `relationships` as another clean alternative that's already commonly used when discussing schemas.

Items and item sounds too generic and more likely for someone to actually have "items" and "item" as a type in their schema... I think `edges` and `node` are generic and different enough to work for more use cases.. they also stand out more in terms of API key words for a learning process.

**Comment by dschafer** [comment]
The naming on this was pretty tricky; thanks for raising this discussion, it will definitely help inform how we discuss and document these things in the future!

We think of the data that GraphQL fetches as a graph (probably unsurprising given the name of the project!). So for the object that represents a link between two objects in the graph, we chose the name `edge`. We then needed a name for the set of edges, and the phrase "an edge connects two objects in a graph" came to mind; if an edge connects two things, then `connection` as the word for a set of edges seemed reasonable.

The name "association" for this would definitely also have worked, in fact, Facebook's data store Tao uses the terms "objects" and "associations" [1], which is probably why we *didn't* choose that name originally; we didn't want both our storage layer representation of an edge and our API layer representation of an edge to have the same name.

I do think we'll end up sticking with "connection" as the term here; we've used that name in this repo, in https://github.com/facebook/relay, and in a number of other places and tools (including some of Facebook's shipped native client applications), so the cost of renaming at this point would be somewhat high. This is really good feedback on how we can ensure our use of the name is as clear as possible, though; in particular, I think we should make sure it's super clear when we're talking about a DB connection vs. connection between two objects in a graph in our documentation and discussions, and we’ll make sure we do that!

[1] https://www.facebook.com/notes/facebook-engineering/tao-the-power-of-the-graph/10151525983993920

**Comment by dschafer** [comment]
Thanks for raising this discussion!

**Comment by mhart** [comment]
Yeah, pity – I get why you've named this concepts in the way you have – because you're steeped in graph land. Problem is most users aren't, especially when it comes to modelling their domain – where concepts like associations and children are much more common and well understood.

I've seen newbies on both Twitter and Slack run into this naming confusion already, and it's going to keep happening.

In any case, better documentation would definitely help. So making it extra extra clear that "connection" has nothing to do with a database, and "node" has nothing to do with Node.js (and is potentially confusing when used in two separate places in Relay – one as a top-level field of a query with an ID and another as a child of edges when using connections)
