### ISSUE TITLE
Where do the (`graphql` flowTypes) used in `graphql-relay-js` come from ?

### ISSUE THREAD

**Issue by iamchenxin** [graphql/graphql-relay-js#85]
I saw some imported type from `graphql`.
like [connection.js#L20](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L20) :
```
import type {
  GraphQLFieldConfigArgumentMap,
  GraphQLFieldConfigMap
} from 'graphql';
```
But i can neither find `.js.flow` output in `graphql`'s package, nor a ".flowconfig"-style lib, and there is also no `graphql` in flow's lib too.
So where do these types come from? Did the type check pass ,just because if flow can not found a flowed package, it will set those type to `any type`? 
Or is there some new  way for outputting flowTypes?
:D

**Comment by sibelius** [comment]
@iamchenxin please try this https://github.com/flowtype/flow-typed
