### ISSUE TITLE
Is there some good way to type check with `graphql` ?

### ISSUE THREAD

**Issue by iamchenxin** [graphql/graphql-relay-js#88]
I used a flow-type output version `graphql-relay-js` in my project. And at this time the `graphql/graphql-relay-js`'s master branch have some unpassed flow-type check.
The most critical part for type check is something like `resolve`.( Cause raw graphql allow source to mixed type.and args to a simple map, Where Relay narrowed source to object ,and use a single `input` key for args. And ,the most of unpassed type checks in `graphql-relay` with `graphql` are caused by this).

`GraphQLFieldResolveFn` [(graphql#L469)](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L469)

```
type GraphQLFieldResolveFn = (
  source: mixed,
  args: {[argName: string]: mixed},
  context: mixed,
  info: GraphQLResolveInfo
) => mixed
```

which in Relay should be something like :

```
ype RelayFieldResolveFn = (
  source: Object,
  args: {'input':Object},
  context: mixed,
  info: GraphQLResolveInfo
) => mixed
```

Is there some elegant way to type check `graphql-relay` with `graphql` ( and narrowed resolveFn rightly)?
i got two idea,but
seems modified `GraphQLFieldResolveFn` to some template type will lead to lots of changes in graphql.
And adding some rumtime check in `graphql-relay` looks like inefficiently.
Is there some good way to do this?

**Comment by MattMcFarland** [comment]
Hey!

I think this is a great question and interesting problem.  I wanted to share how I've solved this especially given some constraints where using flow-type was not possible.  In no way I'm saying this is the best way of doing it, but nonetheless I hope this helps.

1. You can check the constructor name:
http://jsbin.com/liwiwomayu/edit?js,console
```javascript
  const Foo = function () {};

  let foo = new Foo();

  console.log(foo.constructor.name);

```

I hope that is convincing enough, but you can actually find out if something is a GraphQLEnum, GraphQLList, GraphQLObjectType, etc, etc.

But I won't stop here!

Another interesting thing is you can see a graphql object's type config like this:

```javascript
console.log(someGraphQLObject._typeConfig);

// That will actually output something very close to the code you wrote

// the type name:
console.log(myGqlObject._typeConfig.name);
```

You could always use `typeof` with a bunch of ampersands to do the trick as well.  you could also try using `instanceof` as well but I think `constructor.name` is easier to use.

Another way is creating a special tag like `graphType` - in your database for every object and pass it into the Type Resolver function as well.

Hope this helps and honestly I'd love to see what others have done to solve this as well

**Comment by iamchenxin** [comment]
@MattMcFarland Thank you , im finding some way to do a static check. 
In abstract concept,this problem is like this:
  `relayResolver` <- `Graphql` -> `relayResolver`, where  `Graphql`  is a black box. and `relayResolver` use a subset of `Graphql`'s `resolver`. So it should be static check easy.
if in a static language ,there should be  a standard Template style to solve this. But with javascript, `graphql`'s code separate `source` and `args`'s type in many places.
I wonder if there is some inner technology like `React`'s '$ flow method' to do this?
Or may be i should use `any` type to make this part as a black-box of `Graphql` ? 
[there is a `graphql-relay` fork with flow-typed Graphql](https://github.com/iamchenxin/graphql-relay-js/tree/dev-flow4) .

**Comment by sibelius** [comment]
any more work on this?

**Comment by IvanGoncharov** [comment]
Sorry for the late reply.
This issue is not specific to relay-style mutations and already discussed in the graphql-js repo.
