### ISSUE TITLE
Make `typeResolver` optional in `nodeDefinitions`

### ISSUE THREAD

**Issue by mhart** [graphql/graphql-relay-js#9]
AFAICT `graphql-js` allows you to leave out `resolveType` here:

https://github.com/graphql/graphql-js/blob/a149b89a3047f38750eaade1f220eb1317eb9217/src/type/definition.js#L684-L685

In which case it will fall back to using `getTypeOf`/`isTypeOf`

The problem is, `nodeDefinitions` doesn't seem to allow you to leave out the `typeResolver` function:

https://github.com/graphql/graphql-relay-js/blob/3dd1fc334879716e034f6a9583a13813959b0a8f/src/node/node.js#L55

Making this optional would certainly reduce a lot of boilerplate code

**Comment by mhart** [comment]
(FWIW, this is more of a Flow/type issue, not an in-practice issue)

**Comment by dschafer** [comment]
Yep, good call, we should do this.

**Comment by mhart** [comment]
Awesome, thanks :+1:
